// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYGElPe-2N2uGgGxxfjO6_yAuEbZ3bVN0',
    appId: '1:858291132203:web:e11bc4962a017281ae976e',
    messagingSenderId: '858291132203',
    projectId: 'parking-management-syste-cf110',
    authDomain: 'parking-management-syste-cf110.firebaseapp.com',
    storageBucket: 'parking-management-syste-cf110.firebasestorage.app',
    measurementId: 'G-2PGG9ZG9M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcLQwhSdhnKq80KqvcE2vidbu1kQ0yrUc',
    appId: '1:858291132203:android:848fa58d331eefcbae976e',
    messagingSenderId: '858291132203',
    projectId: 'parking-management-syste-cf110',
    storageBucket: 'parking-management-syste-cf110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtapMy0PReE2aeijARh98Yo_c4kBULMbU',
    appId: '1:858291132203:ios:663889a16dd86013ae976e',
    messagingSenderId: '858291132203',
    projectId: 'parking-management-syste-cf110',
    storageBucket: 'parking-management-syste-cf110.firebasestorage.app',
    iosBundleId: 'com.example.parkingManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtapMy0PReE2aeijARh98Yo_c4kBULMbU',
    appId: '1:858291132203:ios:663889a16dd86013ae976e',
    messagingSenderId: '858291132203',
    projectId: 'parking-management-syste-cf110',
    storageBucket: 'parking-management-syste-cf110.firebasestorage.app',
    iosBundleId: 'com.example.parkingManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYGElPe-2N2uGgGxxfjO6_yAuEbZ3bVN0',
    appId: '1:858291132203:web:f0efbb475d9e4040ae976e',
    messagingSenderId: '858291132203',
    projectId: 'parking-management-syste-cf110',
    authDomain: 'parking-management-syste-cf110.firebaseapp.com',
    storageBucket: 'parking-management-syste-cf110.firebasestorage.app',
    measurementId: 'G-PHGR6F38L1',
  );
}
